<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateKontrolsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('kontrols', function (Blueprint $table) {
            $table->id();

            $table->foreignId('fup_id')->constrained('fups')
            ->onDelete('cascade')
            ->onUpdate('cascade');

            $table->string('ru_tlp')->nullable();
            $table->string('ru_pic')->nullable();
            $table->string('ru_dok')->nullable();
            $table->string('ru_status')->nullable();
            $table->date('ru_date')->nullable();
            $table->string('ru_rencana')->nullable();
            $table->string('ru_realisasi')->nullable();

            $table->string('ri_tlp')->nullable();
            $table->string('ri_pic')->nullable();
            $table->string('ri_dok')->nullable();
            $table->string('ri_status')->nullable();
            $table->date('ri_date')->nullable();
            $table->string('ri_rencana')->nullable();
            $table->string('ri_realisasi')->nullable();

            $table->string('st_tlp')->nullable();
            $table->string('st_pic')->nullable();
            $table->string('st_dok')->nullable();
            $table->string('st_status')->nullable();
            $table->date('st_date')->nullable();
            $table->string('st_rencana')->nullable();
            $table->string('st_realisasi')->nullable();
            $table->string('st_tlp2')->nullable();
            $table->string('st_pic2')->nullable();
            $table->string('st_dok2')->nullable();
            $table->string('st_status2')->nullable();
            $table->date('st_date2')->nullable();
            $table->string('st_rencana2')->nullable();
            $table->string('st_realisasi2')->nullable();

            $table->string('me_tlp')->nullable();
            $table->string('me_pic')->nullable();
            $table->string('me_dok')->nullable();
            $table->string('me_status')->nullable();
            $table->date('me_date')->nullable();
            $table->string('me_rencana')->nullable();
            $table->string('me_realisasi')->nullable();
            $table->string('me_tlp2')->nullable();
            $table->string('me_pic2')->nullable();
            $table->string('me_dok2')->nullable();
            $table->string('me_status2')->nullable();
            $table->date('me_date2')->nullable();
            $table->string('me_rencana2')->nullable();
            $table->string('me_realisasi2')->nullable();

            $table->string('val_tlp')->nullable();
            $table->string('val_pic')->nullable();
            $table->string('val_dok')->nullable();
            $table->string('val_status')->nullable();
            $table->date('val_date')->nullable();
            $table->string('val_rencana')->nullable();
            $table->string('val_realisasi')->nullable();
            $table->string('val_tlp2')->nullable();
            $table->string('val_pic2')->nullable();
            $table->string('val_dok2')->nullable();
            $table->string('val_status2')->nullable();
            $table->date('val_date2')->nullable();
            $table->string('val_rencana2')->nullable();
            $table->string('val_realisasi2')->nullable();
            $table->string('val_tlp3')->nullable();
            $table->string('val_pic3')->nullable();
            $table->string('val_dok3')->nullable();
            $table->string('val_status3')->nullable();
            $table->date('val_date3')->nullable();
            $table->string('val_rencana3')->nullable();
            $table->string('val_realisasi3')->nullable();
            $table->string('val_tlp4')->nullable();
            $table->string('val_pic4')->nullable();
            $table->string('val_dok4')->nullable();
            $table->string('val_status4')->nullable();
            $table->date('val_date4')->nullable();
            $table->string('val_rencana4')->nullable();
            $table->string('val_realisasi4')->nullable();
            $table->string('val_tlp5')->nullable();
            $table->string('val_pic5')->nullable();
            $table->string('val_dok5')->nullable();
            $table->date('val_status5')->nullable();
            $table->string('val_date5')->nullable();
            $table->string('val_rencana5')->nullable();
            $table->string('val_realisasi5')->nullable();
            $table->string('val_tlp6')->nullable();
            $table->string('val_pic6')->nullable();
            $table->string('val_dok6')->nullable();
            $table->string('val_status6')->nullable();
            $table->date('val_date6')->nullable();
            $table->string('val_rencana6')->nullable();
            $table->string('val_realisasi6')->nullable();
            $table->string('val_tlp7')->nullable();
            $table->string('val_pic7')->nullable();
            $table->string('val_dok7')->nullable();
            $table->string('val_status7')->nullable();
            $table->date('val_date7')->nullable();
            $table->string('val_rencana7')->nullable();
            $table->string('val_realisasi7')->nullable();
            $table->string('val_tlp8')->nullable();
            $table->string('val_pic8')->nullable();
            $table->string('val_dok8')->nullable();
            $table->string('val_status8')->nullable();
            $table->date('val_date8')->nullable();
            $table->string('val_rencana8')->nullable();
            $table->string('val_realisasi8')->nullable();
            $table->string('val_tlp9')->nullable();
            $table->string('val_pic9')->nullable();
            $table->string('val_dok9')->nullable();
            $table->string('val_status9')->nullable();
            $table->date('val_date9')->nullable();
            $table->string('val_rencana9')->nullable();
            $table->string('val_realisasi9')->nullable();
            $table->string('val_tlp10')->nullable();
            $table->string('val_pic10')->nullable();
            $table->string('val_dok10')->nullable();
            $table->string('val_status10')->nullable();
            $table->date('val_date10')->nullable();
            $table->string('val_rencana10')->nullable();
            $table->string('val_realisasi10')->nullable();
            $table->string('val_tlp11')->nullable();
            $table->string('val_pic11')->nullable();
            $table->string('val_dok11')->nullable();
            $table->string('val_status11')->nullable();
            $table->date('val_date11')->nullable();
            $table->string('val_rencana11')->nullable();
            $table->string('val_realisasi11')->nullable();
            $table->string('val_tlp12')->nullable();
            $table->string('val_pic12')->nullable();
            $table->string('val_dok12')->nullable();
            $table->string('val_status12')->nullable();
            $table->date('val_date12')->nullable();
            $table->string('val_rencana12')->nullable();
            $table->string('val_realisasi12')->nullable();
            $table->string('val_tlp13')->nullable();
            $table->string('val_pic13')->nullable();
            $table->string('val_dok13')->nullable();
            $table->string('val_status13')->nullable();
            $table->date('val_date13')->nullable();
            $table->string('val_rencana13')->nullable();
            $table->string('val_realisasi13')->nullable();
            $table->string('val_tlp14')->nullable();
            $table->string('val_pic14')->nullable();
            $table->string('val_dok14')->nullable();
            $table->string('val_status14')->nullable();
            $table->date('val_date14')->nullable();
            $table->string('val_rencana14')->nullable();
            $table->string('val_realisasi14')->nullable();

            $table->string('tr_tlp')->nullable();
            $table->string('tr_pic')->nullable();
            $table->string('tr_dok')->nullable();
            $table->string('tr_status')->nullable();
            $table->date('tr_date')->nullable();
            $table->string('tr_rencana')->nullable();
            $table->string('tr_realisasi')->nullable();
            $table->string('tr_tlp2')->nullable();
            $table->string('tr_pic2')->nullable();
            $table->string('tr_dok2')->nullable();
            $table->string('tr_status2')->nullable();
            $table->date('tr_date2')->nullable();
            $table->string('tr_rencana2')->nullable();
            $table->string('tr_realisasi2')->nullable();
            $table->string('tr_tlp3')->nullable();
            $table->string('tr_pic3')->nullable();
            $table->string('tr_dok3')->nullable();
            $table->string('tr_status3')->nullable();
            $table->date('tr_date3')->nullable();
            $table->string('tr_rencana3')->nullable();
            $table->string('tr_realisasi3')->nullable();
            $table->string('tr_tlp4')->nullable();
            $table->string('tr_pic4')->nullable();
            $table->string('tr_dok4')->nullable();
            $table->string('tr_status4')->nullable();
            $table->date('tr_date4')->nullable();
            $table->string('tr_rencana4')->nullable();
            $table->string('tr_realisasi4')->nullable();
            $table->string('tr_tlp5')->nullable();
            $table->string('tr_pic5')->nullable();
            $table->string('tr_dok5')->nullable();
            $table->string('tr_status5')->nullable();
            $table->date('tr_date5')->nullable();
            $table->string('tr_rencana5')->nullable();
            $table->string('tr_realisasi5')->nullable();
            $table->string('tr_tlp6')->nullable();
            $table->string('tr_pic6')->nullable();
            $table->string('tr_dok6')->nullable();
            $table->string('tr_status6')->nullable();
            $table->date('tr_date6')->nullable();
            $table->string('tr_rencana6')->nullable();
            $table->string('tr_realisasi6')->nullable();

            $table->string('pro_tlp')->nullable();
            $table->string('pro_pic')->nullable();
            $table->string('pro_dok')->nullable();
            $table->string('pro_status')->nullable();
            $table->date('pro_date')->nullable();
            $table->string('pro_rencana')->nullable();
            $table->string('pro_realisasi')->nullable();
            $table->string('pro_tlp2')->nullable();
            $table->string('pro_pic2')->nullable();
            $table->string('pro_dok2')->nullable();
            $table->string('pro_status2')->nullable();
            $table->date('pro_date2')->nullable();
            $table->string('pro_rencana2')->nullable();
            $table->string('pro_realisasi2')->nullable();
            $table->string('pro_tlp3')->nullable();
            $table->string('pro_pic3')->nullable();
            $table->string('pro_dok3')->nullable();
            $table->string('pro_status3')->nullable();
            $table->date('pro_date3')->nullable();
            $table->string('pro_rencana3')->nullable();
            $table->string('pro_realisasi3')->nullable();

            $table->string('dok_tlp')->nullable();
            $table->string('dok_pic')->nullable();
            $table->string('dok_dok')->nullable();
            $table->string('dok_status')->nullable();
            $table->string('dok_date')->nullable();
            $table->string('dok_rencana')->nullable();
            $table->string('dok_realisasi')->nullable();
            $table->string('dok_tlp2')->nullable();
            $table->string('dok_pic2')->nullable();
            $table->string('dok_dok2')->nullable();
            $table->string('dok_status2')->nullable();
            $table->string('dok_date2')->nullable();
            $table->string('dok_rencana2')->nullable();
            $table->string('dok_realisasi2')->nullable();
            $table->string('dok_tlp3')->nullable();
            $table->string('dok_pic3')->nullable();
            $table->string('dok_dok3')->nullable();
            $table->string('dok_status3')->nullable();
            $table->string('dok_date3')->nullable();
            $table->string('dok_rencana3')->nullable();
            $table->string('dok_realisasi3')->nullable();
            $table->string('dok_tlp4')->nullable();
            $table->string('dok_pic4')->nullable();
            $table->string('dok_dok4')->nullable();
            $table->string('dok_status4')->nullable();
            $table->string('dok_date4')->nullable();
            $table->string('dok_rencana4')->nullable();
            $table->string('dok_realisasi4')->nullable();
            $table->string('dok_tlp5')->nullable();
            $table->string('dok_pic5')->nullable();
            $table->string('dok_dok5')->nullable();
            $table->string('dok_status5')->nullable();
            $table->string('dok_date5')->nullable();
            $table->string('dok_rencana5')->nullable();
            $table->string('dok_realisasi5')->nullable();
            $table->string('dok_tlp6')->nullable();
            $table->string('dok_pic6')->nullable();
            $table->string('dok_dok6')->nullable();
            $table->string('dok_status6')->nullable();
            $table->string('dok_date6')->nullable();
            $table->string('dok_rencana6')->nullable();
            $table->string('dok_realisasi6')->nullable();
            $table->string('dok_tlp7')->nullable();
            $table->string('dok_pic7')->nullable();
            $table->string('dok_dok7')->nullable();
            $table->string('dok_status7')->nullable();
            $table->string('dok_date7')->nullable();
            $table->string('dok_rencana7')->nullable();
            $table->string('dok_realisasi7')->nullable();
            $table->string('dok_tlp8')->nullable();
            $table->string('dok_pic8')->nullable();
            $table->string('dok_dok8')->nullable();
            $table->string('dok_status8')->nullable();
            $table->string('dok_date8')->nullable();
            $table->string('dok_rencana8')->nullable();
            $table->string('dok_realisasi8')->nullable();
            $table->string('dok_tlp9')->nullable();
            $table->string('dok_pic9')->nullable();
            $table->string('dok_dok9')->nullable();
            $table->string('dok_status9')->nullable();
            $table->string('dok_date9')->nullable();
            $table->string('dok_rencana9')->nullable();
            $table->string('dok_realisasi9')->nullable();

            $table->string('sis_tlp')->nullable();
            $table->string('sis_pic')->nullable();
            $table->string('sis_dok')->nullable();
            $table->string('sis_status')->nullable();
            $table->date('sis_date')->nullable();
            $table->string('sis_rencana')->nullable();
            $table->string('sis_realisasi')->nullable();

            $table->string('hasil_mitigasi')->nullable();
            $table->string('dis_setuju')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('kontrols');
    }
}
