<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateKontrolsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('kontrols', function (Blueprint $table) {
            $table->id();

            $table->foreignId('fup_id')->constrained('fups')
            ->onDelete('cascade')
            ->onUpdate('cascade');

            $table->string('ru_tlp');
            $table->string('ru_pic');
            $table->string('ru_dok');
            $table->string('ru_status');
            $table->date('ru_date');
            $table->string('ru_rencana');
            $table->string('ru_realisasi');

            $table->string('ri_tlp');
            $table->string('ri_pic');
            $table->string('ri_dok');
            $table->string('ri_status');
            $table->date('ri_date');
            $table->string('ri_rencana');
            $table->string('ri_realisasi');

            $table->string('st_tlp');
            $table->string('st_pic');
            $table->string('st_dok');
            $table->string('st_status');
            $table->date('st_date');
            $table->string('st_rencana');
            $table->string('st_realisasi');
            $table->string('st_tlp2');
            $table->string('st_pic2');
            $table->string('st_dok2');
            $table->string('st_status2');
            $table->date('st_date2');
            $table->string('st_rencana2');
            $table->string('st_realisasi2');

            $table->string('me_tlp');
            $table->string('me_pic');
            $table->string('me_dok');
            $table->string('me_status');
            $table->date('me_date');
            $table->string('me_rencana');
            $table->string('me_realisasi');
            $table->string('me_tlp2');
            $table->string('me_pic2');
            $table->string('me_dok2');
            $table->string('me_status2');
            $table->date('me_date2');
            $table->string('me_rencana2');
            $table->string('me_realisasi2');

            $table->string('val_tlp');
            $table->string('val_pic');
            $table->string('val_dok');
            $table->string('val_status');
            $table->date('val_date');
            $table->string('val_rencana');
            $table->string('val_realisasi');
            $table->string('val_tlp2');
            $table->string('val_pic2');
            $table->string('val_dok2');
            $table->string('val_status2');
            $table->date('val_date2');
            $table->string('val_rencana2');
            $table->string('val_realisasi2');
            $table->string('val_tlp3');
            $table->string('val_pic3');
            $table->string('val_dok3');
            $table->string('val_status3');
            $table->date('val_date3');
            $table->string('val_rencana3');
            $table->string('val_realisasi3');
            $table->string('val_tlp4');
            $table->string('val_pic4');
            $table->string('val_dok4');
            $table->string('val_status4');
            $table->date('val_date4');
            $table->string('val_rencana4');
            $table->string('val_realisasi4');
            $table->string('val_tlp5');
            $table->string('val_pic5');
            $table->string('val_dok5');
            $table->date('val_status5');
            $table->string('val_date5');
            $table->string('val_rencana5');
            $table->string('val_realisasi5');
            $table->string('val_tlp6');
            $table->string('val_pic6');
            $table->string('val_dok6');
            $table->string('val_status6');
            $table->date('val_date6');
            $table->string('val_rencana6');
            $table->string('val_realisasi6');
            $table->string('val_tlp7');
            $table->string('val_pic7');
            $table->string('val_dok7');
            $table->string('val_status7');
            $table->date('val_date7');
            $table->string('val_rencana7');
            $table->string('val_realisasi7');
            $table->string('val_tlp8');
            $table->string('val_pic8');
            $table->string('val_dok8');
            $table->string('val_status8');
            $table->date('val_date8');
            $table->string('val_rencana8');
            $table->string('val_realisasi8');
            $table->string('val_tlp9');
            $table->string('val_pic9');
            $table->string('val_dok9');
            $table->string('val_status9');
            $table->date('val_date9');
            $table->string('val_rencana9');
            $table->string('val_realisasi9');
            $table->string('val_tlp10');
            $table->string('val_pic10');
            $table->string('val_dok10');
            $table->string('val_status10');
            $table->date('val_date10');
            $table->string('val_rencana10');
            $table->string('val_realisasi10');
            $table->string('val_tlp11');
            $table->string('val_pic11');
            $table->string('val_dok11');
            $table->string('val_status11');
            $table->date('val_date11');
            $table->string('val_rencana11');
            $table->string('val_realisasi11');
            $table->string('val_tlp12');
            $table->string('val_pic12');
            $table->string('val_dok12');
            $table->string('val_status12');
            $table->date('val_date12');
            $table->string('val_rencana12');
            $table->string('val_realisasi12');
            $table->string('val_tlp13');
            $table->string('val_pic13');
            $table->string('val_dok13');
            $table->string('val_status13');
            $table->date('val_date13');
            $table->string('val_rencana13');
            $table->string('val_realisasi13');
            $table->string('val_tlp14');
            $table->string('val_pic14');
            $table->string('val_dok14');
            $table->string('val_status14');
            $table->date('val_date14');
            $table->string('val_rencana14');
            $table->string('val_realisasi14');

            $table->string('tr_tlp');
            $table->string('tr_pic');
            $table->string('tr_dok');
            $table->string('tr_status');
            $table->date('tr_date');
            $table->string('tr_rencana');
            $table->string('tr_realisasi');
            $table->string('tr_tlp2');
            $table->string('tr_pic2');
            $table->string('tr_dok2');
            $table->string('tr_status2');
            $table->date('tr_date2');
            $table->string('tr_rencana2');
            $table->string('tr_realisasi2');
            $table->string('tr_tlp3');
            $table->string('tr_pic3');
            $table->string('tr_dok3');
            $table->string('tr_status3');
            $table->date('tr_date3');
            $table->string('tr_rencana3');
            $table->string('tr_realisasi3');
            $table->string('tr_tlp4');
            $table->string('tr_pic4');
            $table->string('tr_dok4');
            $table->string('tr_status4');
            $table->date('tr_date4');
            $table->string('tr_rencana4');
            $table->string('tr_realisasi4');
            $table->string('tr_tlp5');
            $table->string('tr_pic5');
            $table->string('tr_dok5');
            $table->string('tr_status5');
            $table->date('tr_date5');
            $table->string('tr_rencana5');
            $table->string('tr_realisasi5');
            $table->string('tr_tlp6');
            $table->string('tr_pic6');
            $table->string('tr_dok6');
            $table->string('tr_status6');
            $table->date('tr_date6');
            $table->string('tr_rencana6');
            $table->string('tr_realisasi6');

            $table->string('pro_tlp');
            $table->string('pro_pic');
            $table->string('pro_dok');
            $table->string('pro_status');
            $table->date('pro_date');
            $table->string('pro_rencana');
            $table->string('pro_realisasi');
            $table->string('pro_tlp2');
            $table->string('pro_pic2');
            $table->string('pro_dok2');
            $table->string('pro_status2');
            $table->date('pro_date2');
            $table->string('pro_rencana2');
            $table->string('pro_realisasi2');
            $table->string('pro_tlp3');
            $table->string('pro_pic3');
            $table->string('pro_dok3');
            $table->string('pro_status3');
            $table->date('pro_date3');
            $table->string('pro_rencana3');
            $table->string('pro_realisasi3');

            $table->string('dok_tlp');
            $table->string('dok_pic');
            $table->string('dok_dok');
            $table->string('dok_status');
            $table->string('dok_date');
            $table->string('dok_rencana');
            $table->string('dok_realisasi');
            $table->string('dok_tlp2');
            $table->string('dok_pic2');
            $table->string('dok_dok2');
            $table->string('dok_status2');
            $table->string('dok_date2');
            $table->string('dok_rencana2');
            $table->string('dok_realisasi2');
            $table->string('dok_tlp3');
            $table->string('dok_pic3');
            $table->string('dok_dok3');
            $table->string('dok_status3');
            $table->string('dok_date3');
            $table->string('dok_rencana3');
            $table->string('dok_realisasi3');
            $table->string('dok_tlp4');
            $table->string('dok_pic4');
            $table->string('dok_dok4');
            $table->string('dok_status4');
            $table->string('dok_date4');
            $table->string('dok_rencana4');
            $table->string('dok_realisasi4');
            $table->string('dok_tlp5');
            $table->string('dok_pic5');
            $table->string('dok_dok5');
            $table->string('dok_status5');
            $table->string('dok_date5');
            $table->string('dok_rencana5');
            $table->string('dok_realisasi5');
            $table->string('dok_tlp6');
            $table->string('dok_pic6');
            $table->string('dok_dok6');
            $table->string('dok_status6');
            $table->string('dok_date6');
            $table->string('dok_rencana6');
            $table->string('dok_realisasi6');
            $table->string('dok_tlp7');
            $table->string('dok_pic7');
            $table->string('dok_dok7');
            $table->string('dok_status7');
            $table->string('dok_date7');
            $table->string('dok_rencana7');
            $table->string('dok_realisasi7');
            $table->string('dok_tlp8');
            $table->string('dok_pic8');
            $table->string('dok_dok8');
            $table->string('dok_status8');
            $table->string('dok_date8');
            $table->string('dok_rencana8');
            $table->string('dok_realisasi8');
            $table->string('dok_tlp9');
            $table->string('dok_pic9');
            $table->string('dok_dok9');
            $table->string('dok_status9');
            $table->string('dok_date9');
            $table->string('dok_rencana9');
            $table->string('dok_realisasi9');

            $table->string('sis_tlp');
            $table->string('sis_pic');
            $table->string('sis_dok');
            $table->string('sis_status');
            $table->date('sis_date');
            $table->string('sis_rencana');
            $table->string('sis_realisasi');

            $table->string('hasil_mitigasi');
            $table->string('dis_setuju');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('kontrols');
    }
}
